export const CREATE_CHANNEL_ERROR = 'CREATE_CHANNEL_ERROR';
export const CREATE_CHANNEL_SUCCESS = 'CREATE_CHANNEL_SUCCESS';

export const DELETE_CHANNEL_ERROR = 'DELETE_CHANNEL_ERROR';
export const DELETE_CHANNEL_SUCCESS = 'DELETE_CHANNEL_SUCCESS';

export const UNDELETE_CHANNEL_ERROR = 'UNDELETE_CHANNEL_ERROR';

export const UPDATE_CHANNEL_ERROR = 'UPDATE_CHANNEL_ERROR';
export const UPDATE_CHANNEL_SUCCESS = 'UPDATE_CHANNEL_SUCCESS';

export const FILTER_CHANNELS = 'FILTER_CHANNELS';
export const LOAD_CHANNELS_SUCCESS = 'LOAD_CHANNELS_SUCCESS';
export const UNLOAD_CHANNELS_SUCCESS = 'UNLOAD_CHANNELS_SUCCESS';
