export const LOAD_USERS_SUCCESS = 'LOAD_USERS_SUCCESS';
export const UNLOAD_USERS_SUCCESS = 'UNLOAD_USERS_SUCCESS';

export const CREATE_USER_ERROR = 'CREATE_USER_ERROR';
export const CREATE_USER_SUCCESS = 'CREATE_USER_SUCCESS';

export const UPDATE_USER_SUCCESS = 'UPDATE_USER_SUCCESS';
export const UPDATE_USER_ERROR = 'UPDATE_USER_ERROR';
